public static void printFace(){
    System.out.println("                                      .....'',;;::cccllllllllllllcccc:::;;,,,''...'',,'..");
    System.out.println("                            ..';cldkO00KXNNNNXXXKK000OOkkkkkxxxxxddoooddddddxxxxkkkkOO0XXKx:.");
    System.out.println("                      .':ok0KXXXNXK0kxolc:;;,,,,,,,,,,,;;,,,''''''',,''..              .'lOXKd'");
    System.out.println("                 .,lx00Oxl:,'............''''''...................    ...,;;'.             .oKXd.");
    System.out.println("              .ckKKkc'...'',:::;,'.........'',;;::::;,'..........'',;;;,'.. .';;'.           'kNKc.");
    System.out.println("           .:kXXk:.    ..       ..................          .............,:c:'...;:'.         .dNNx.");
    System.out.println("          :0NKd,          .....''',,,,''..               ',...........',,,'',,::,...,,.        .dNNx.");
    System.out.println("         .xXd.         .:;'..         ..,'             .;,.               ...,,'';;'. ...       .oNNo");
    System.out.println("         .0K.         .;.              ;'              ';                      .'...'.           .oXX:");
    System.out.println("        .oNO.         .                 ,.              .     ..',::ccc:;,..     ..                lXX:");
    System.out.println("       .dNX:               ......       ;.                'cxOKK0OXWWWWWWWNX0kc.                    :KXd.");
    System.out.println("     .l0N0;             ;d0KKKKKXK0ko:...              .l0X0xc,...lXWWWWWWWWKO0Kx'                   ,ONKo.");
    System.out.println("   .lKNKl...'......'. .dXWN0kkk0NWWWWWN0o.            :KN0;.  .,cokXWWNNNNWNKkxONK: .,:c:.      .';;;;:lk0XXx;");
    System.out.println("  :KN0l';ll:'.         .,:lodxxkO00KXNWWWX000k.       oXNx;:okKX0kdl:::;'',;coxkkd, ...'. ...'''.......',:lxKO:.");
    System.out.println(" oNNk,;c,'',.                      ...;xNNOc,.         ,d0X0xc,.     .dOd,           ..;dOKXK00000Ox:.   ..''dKO,");
    System.out.println("'KW0,:,.,:..,oxkkkdl;'.                'KK'              ..           .dXX0o:'....,:oOXNN0d;.'. ..,lOKd.   .. ;KXl.");
    System.out.println(";XNd,;  ;. l00kxoooxKXKx:..ld:         ;KK'                             .:dkO000000Okxl;.   c0;      :KK;   .  ;XXc");
    System.out.println("'XXdc.  :. ..    '' 'kNNNKKKk,      .,dKNO.                                   ....       .'c0NO'      :X0.  ,.  xN0.");
    System.out.println(".kNOc'  ,.      .00. ..''...      .l0X0d;.             'dOkxo;...                    .;okKXK0KNXx;.   .0X:  ,.  lNX'");
    System.out.println(" ,KKdl  .c,    .dNK,            .;xXWKc.                .;:coOXO,,'.......       .,lx0XXOo;...oNWNXKk:.'KX;  '   dNX.");
    System.out.println("  :XXkc'....  .dNWXl        .';l0NXNKl.          ,lxkkkxo' .cK0.          ..;lx0XNX0xc.     ,0Nx'.','.kXo  .,  ,KNx.");
    System.out.println("   cXXd,,;:, .oXWNNKo'    .'..  .'.'dKk;        .cooollox;.xXXl     ..,cdOKXXX00NXc.      'oKWK'     ;k:  .l. ,0Nk.");
    System.out.println("    cXNx.  . ,KWX0NNNXOl'.           .o0Ooldk;            .:c;.':lxOKKK0xo:,.. ;XX:   .,lOXWWXd.      . .':,.lKXd.");
    System.out.println("     lXNo    cXWWWXooNWNXKko;'..       .lk0x;       ...,:ldk0KXNNOo:,..       ,OWNOxO0KXXNWNO,        ....'l0Xk,");
    System.out.println("     .dNK.   oNWWNo.cXK;;oOXNNXK0kxdolllllooooddxk00KKKK0kdoc:c0No        .'ckXWWWNXkc,;kNKl.          .,kXXk,");
    System.out.println("      'KXc  .dNWWX;.xNk.  .kNO::lodxkOXWN0OkxdlcxNKl,..        oN0'..,:ox0XNWWNNWXo.  ,ONO'           .o0Xk;");
    System.out.println("      .ONo    oNWWN0xXWK, .oNKc       .ONx.      ;X0.          .:XNKKNNWWWWNKkl;kNk. .cKXo.           .ON0;");
    System.out.println("      .xNd   cNWWWWWWWWKOkKNXxl:,'...;0Xo'.....'lXK;...',:lxk0KNWWWWNNKOd:..   lXKclON0:            .xNk.");
    System.out.println("      .dXd   ;XWWWWWWWWWWWWWWWWWWNNNNNWWNNNNNNNNNWWNNNNNNWWWWWNXKNNk;..        .dNWWXd.             cXO.");
    System.out.println("      .xXo   .ONWNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNK0ko:'..OXo          'l0NXx,              :KK,");
    System.out.println("      .OXc    :XNk0NWXKNWWWWWWWWWWWWWWWWWWWWWNNNX00NNx:'..       lXKc.     'lONN0l.              .oXK:");
    System.out.println("      .KX;    .dNKoON0;lXNkcld0NXo::cd0NNO:;,,'.. .0Xc            lXXo..'l0NNKd,.              .c0Nk,");
    System.out.println("      :XK.     .xNX0NKc.cXXl  ;KXl    .dN0.       .0No            .xNXOKNXOo,.               .l0Xk;.");
    System.out.println("     .dXk.      .lKWN0d::OWK;  lXXc    .OX:       .ONx.     . .,cdk0XNXOd;.   .'''....;c:'..;xKXx,");
    System.out.println("     .0No         .:dOKNNNWNKOxkXWXo:,,;ONk;,,,,,;c0NXOxxkO0XXNXKOdc,.  ..;::,...;lol;..:xKXOl.");
    System.out.println("     ,XX:             ..';cldxkOO0KKKXXXXXXXXXXKKKKK00Okxdol:;'..   .';::,..':llc,..'lkKXkc.");
    System.out.println("     :NX'    .     ''            ..................             .,;:;,',;ccc;'..'lkKX0d;.");
    System.out.println("     lNK.   .;      ,lc,.         ................        ..,,;;;;;;:::,....,lkKX0d:.");
    System.out.println("    .oN0.    .'.      .;ccc;,'....              ....'',;;;;;;;;;;'..   .;oOXX0d:.");
    System.out.println("    .dN0.      .;;,..       ....                ..''''''''....     .:dOKKko;.");
    System.out.println("     lNK'         ..,;::;;,'.........................           .;d0X0kc'.");
    System.out.println("     .xXO'                                                 .;oOK0x:.");
    System.out.println("      .cKKo.                                    .,:oxkkkxk0K0xc'.");
    System.out.println("        .oKKkc,.                         .';cok0XNNNX0Oxoc,.");
    System.out.println("          .;d0XX0kdlc:;,,,',,,;;:clodkO0KK0Okdl:,'..");
    System.out.println("              .,coxO0KXXXXXXXKK0OOxdoc:,..");
    System.out.println("                        ...");
    
  }
